# Generated by Django 3.1.7 on 2021-03-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Имя')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='categories', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('characteristics', models.TextField(blank=True, null=True, verbose_name='Характеристики')),
                ('description', models.CharField(db_index=True, max_length=750, verbose_name='Описаие')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('slug', models.CharField(db_index=True, max_length=250, verbose_name='Ссылка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Масло',
                'verbose_name_plural': 'Масла',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата и время заявки')),
                ('costumer_name', models.CharField(max_length=50, verbose_name='ФИО Клиента')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('message', models.CharField(max_length=1000, verbose_name='Сообщение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.products', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
