# Generated by Django 3.1.4 on 2020-12-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('viscosity', models.CharField(db_index=True, max_length=250, verbose_name='Вязкость при 100°С')),
                ('index_viscosity', models.PositiveIntegerField(verbose_name='Индекс вязкости')),
                ('temp_flash', models.PositiveIntegerField(verbose_name='Температура вспышки')),
                ('temp_solidification', models.PositiveIntegerField(verbose_name='Температура застывания')),
                ('base_number', models.FloatField(blank=True, null=True, verbose_name='Щелочное число')),
                ('density', models.FloatField(blank=True, null=True, verbose_name=' Плотность, при 20° С')),
                ('color', models.FloatField(blank=True, null=True, verbose_name='Цвет с разбавлением')),
                ('description', models.CharField(db_index=True, max_length=250, verbose_name='Описаие')),
                ('slug', models.CharField(db_index=True, max_length=250, verbose_name='Ссылка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Масло',
                'verbose_name_plural': 'Масла',
            },
        ),
    ]
