# Generated by Django 3.1.4 on 2020-12-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='base_number_actually',
            field=models.FloatField(blank=True, null=True, verbose_name='Щелочное число (Фактическое значение)'),
        ),
        migrations.AddField(
            model_name='products',
            name='color_actually',
            field=models.FloatField(blank=True, null=True, verbose_name='Цвет с разбавлением (Фактическое значение)'),
        ),
        migrations.AddField(
            model_name='products',
            name='density_actually',
            field=models.FloatField(blank=True, null=True, verbose_name=' Плотность, при 20° С (Фактическое значение)'),
        ),
        migrations.AddField(
            model_name='products',
            name='index_viscosity_actually',
            field=models.PositiveIntegerField(default=2, verbose_name='Индекс вязкости (Фактическое значение)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='temp_flash_actually',
            field=models.PositiveIntegerField(default=2, verbose_name='Температура вспышки (Фактическое значение)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='temp_solidification_actually',
            field=models.PositiveIntegerField(default=2, verbose_name='Температура застывания (Фактическое значение)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='viscosity_actually',
            field=models.CharField(db_index=True, default=1, max_length=250, verbose_name='Вязкость при 100°С (Фактическое значение)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='base_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Щелочное число (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.FloatField(blank=True, null=True, verbose_name='Цвет с разбавлением (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name=' Плотность, при 20° С (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='index_viscosity',
            field=models.PositiveIntegerField(verbose_name='Индекс вязкости (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='temp_flash',
            field=models.PositiveIntegerField(verbose_name='Температура вспышки (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='temp_solidification',
            field=models.PositiveIntegerField(verbose_name='Температура застывания (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='viscosity',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Вязкость при 100°С (Нормативное значение)'),
        ),
    ]
