# Generated by Django 3.1.4 on 2020-12-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201225_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(db_index=True, max_length=250, verbose_name='Описаие'),
        ),
    ]
