# Generated by Django 3.1.4 on 2020-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201225_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(db_index=True, max_length=750, verbose_name='Описаие'),
        ),
        migrations.AlterField(
            model_name='products',
            name='temp_flash',
            field=models.FloatField(verbose_name='Температура вспышки (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='temp_flash_actually',
            field=models.FloatField(verbose_name='Температура вспышки (Фактическое значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='temp_solidification',
            field=models.FloatField(verbose_name='Температура застывания (Нормативное значение)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='temp_solidification_actually',
            field=models.FloatField(verbose_name='Температура застывания (Фактическое значение)'),
        ),
    ]
