# Generated by Django 3.1.7 on 2021-03-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_categories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата и время заявки')),
                ('costumer_name', models.CharField(max_length=50, verbose_name='ФИО Клиента')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.products', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
